#!/bin/sh
set -eu

APP_DB_USER="${APP_DB_USER:-qrguest_app}"
APP_DB_PASSWORD="${APP_DB_PASSWORD:-qrguest_app}"
APP_SHADOW_DB="${APP_SHADOW_DB:-qrguest_shadow}"
PGHOST="${PGHOST:-localhost}"
PGPORT="${PGPORT:-5432}"

psql -v ON_ERROR_STOP=1 --host "$PGHOST" --port "$PGPORT" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_DB_USER}') THEN
    CREATE ROLE "${APP_DB_USER}" LOGIN PASSWORD '${APP_DB_PASSWORD}';
  ELSE
    ALTER ROLE "${APP_DB_USER}" WITH LOGIN PASSWORD '${APP_DB_PASSWORD}';
  END IF;
END
\$\$;

ALTER ROLE "${APP_DB_USER}" NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS;
GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}";
GRANT CREATE, TEMPORARY ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}";
GRANT USAGE, CREATE ON SCHEMA public TO "${APP_DB_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${APP_DB_USER}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "${APP_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${APP_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${APP_DB_USER}";
EOSQL

if ! psql -v ON_ERROR_STOP=1 --host "$PGHOST" --port "$PGPORT" --username "$POSTGRES_USER" --dbname postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '${APP_SHADOW_DB}'" | grep -q 1; then
  createdb --host "$PGHOST" --port "$PGPORT" --username "$POSTGRES_USER" "$APP_SHADOW_DB"
fi
